spring:
  application.name: turbine

turbine:
  aggregator:
    clusterConfig: default
  appConfig: trend-trading-backtest-service  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")

eureka:
  client:
    serviceUrl:
      defaultZone: http://49.235.218.240:8761/eureka/

server:
  port: 8081