eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://49.235.218.240:8761/eureka/
spring:
  application:
    name: third-part-index-data-project

server:
  port: 8090


