eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: trend-trading-backtest-service
  zipkin:
    base-url: http://localhost:9411

feign.hystrix.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:          # 配置跨域资源共享
        allowed-origins: "*"
        allowed-methods: "*"



hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000