server:
  port: 8051

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://49.235.218.240:8761/eureka/
spring:
  application:
    name: trend-trading-backtest-service
  zipkin:
    base-url: http://47.93.188.100:9411


feign:                          #开启feign的断路器回调
  hystrix:
    enabled: true


management:                             #开启/actuator/hystrix.stream访问权
  endpoints:
    web:
      exposure:
        include: "*"
      cors:          # 配置跨域资源共享
        allowed-origins: "*"
        allowed-methods: "*"



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
