spring:
  application:
    name: index-codes-service
  zipkin:                             #链路追踪
    base-url: http://47.93.188.100:9411
  redis:                              #redis
    host: 49.235.218.240
    port: 6379
    timeout: 1000
    password: 123456


eureka:
  client:
    service-url:
      defaultZone: http://49.235.218.240:8761/eureka/

server:
  port: 8011

