spring:
  application:
    name: index-config-server
  cloud:
    config:
      label: master
      profile: dev
      server:
        git:
          uri: https://gitee.com/m_ls/sys_trend.git
          searchPaths: config-repo

eureka:
  client:
    service-url:
      defaultZone: http://49.235.218.240:8761/eureka/
server:
  port: 8060


