spring:
  application:
    name: index-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/m_ls/sys_trend.git
          searchPaths: config-repo
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
