spring:
  application:
    name: index-data-service
  zipkin:
    base-url: http://47.93.188.100:9411
  redis:                              #redis
    host: 49.235.218.240
    port: 6379
    timeout: 5000
    password: 123456

server:
  port: 8021

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://49.235.218.240:8761/eureka/