eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://49.235.218.240:8761/eureka/

spring:
  application:
    name: index-gather-store-service
  redis:                              #redis
    host: 49.235.218.240
    port: 6379
    timeout: 5000
    password: 123456

server:
  port: 8001

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

thirdPart:
  ipAddress: 127.0.0.1
  port: 8090

